deployName: dashboard-deploy
serviceName: dashboard-service
replicaCount: 1
namespace: theiacloud
app:
  image: sevvalekici/nextjs-docker:latest
  port: 3000
db:
  image: questdb/questdb:latest
  port: 9000
