kind: Service
apiVersion: v1
metadata:
  name: dashboard-service
  namespace: theiacloud
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: { { .Values.app.port } }
  type: LoadBalancer
